export const MOVEMENT_TYPE = {
  DEPOSITO: 'DEPOSITO',
  RETIRO: 'RETIRO',
  TRANSFERENCIA_ENVIADA: 'TRANSFERENCIA_ENVIADA',
  TRANSFERENCIA_RECIBIDA: 'TRANSFERENCIA_RECIBIDA',
  PAGO_SERVICIO: 'PAGO_SERVICIO',
} as const;

export const MOVEMENT_TYPE_LABELS = {
  [MOVEMENT_TYPE.DEPOSITO]: 'Depósito',
  [MOVEMENT_TYPE.RETIRO]: 'Retiro',
  [MOVEMENT_TYPE.TRANSFERENCIA_ENVIADA]: 'Transferencia Enviada',
  [MOVEMENT_TYPE.TRANSFERENCIA_RECIBIDA]: 'Transferencia Recibida',
  [MOVEMENT_TYPE.PAGO_SERVICIO]: 'Pago de Servicio',
} as const;
